management:
  endpoint:
    info:
      access: read_only
    health:
      access: read_only
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /manage
      exposure:
        include:
          - health
          - info
  server:
    port: 9080
    ssl:
      enabled: false
    add-application-context-header: true
spring:
  application:
    name: ok

server:
  port: 8080
  forward-headers-strategy: framework
  shutdown: graceful

logging:
  level:
    ROOT: warn
    nl.appsource: info
#    org.springframework.web: debug
#    org.springframework.security: debug

