management:
  endpoint:
    health:
      probes:
        enabled: true
  server:
    port: 9080
  endpoints:
    web:
      exposure:
        include: health, info
spring:
  application:
    name: ok

server:
  port: 8080


logging:
  level:
    ROOT: info
    nl.appsource: info