# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "liberica"
          cache: maven

      - name: Build container
        run: mvn -Pnative -ntp -B spring-boot:build-image -Dspring-boot.build-image.imageName=europe-west4-docker.pkg.dev/impl-383520/docker/ok:latest

      - id: "auth"
        if: github.event_name != 'pull_request'
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Set up gcloud Cloud SDK environment
        if: github.event_name != 'pull_request'
        uses: google-github-actions/setup-gcloud@v2.1.4
        with:
          project_id: impl-383520

      - name: "Configure docker"
        if: github.event_name != 'pull_request'
        run: gcloud auth configure-docker europe-west4-docker.pkg.dev

      - name: "Push image to GCR"
        if: github.event_name != 'pull_request'
        run: docker push europe-west4-docker.pkg.dev/impl-383520/docker/ok:latest

      - name: "Install kubectl"
        if: github.event_name != 'pull_request'
        run: |
          curl -sLO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubectl"
          chmod 755 ./kubectl

      - name: "Rollout restart"
        if: github.event_name != 'pull_request'
        env:
          KBCONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          echo "${KBCONFIG}" | base64 --decode > /tmp/kube_config
          ./kubectl --kubeconfig /tmp/kube_config rollout restart statefulset -n okapp ok
